# Site settings
title: Steven Stuart
email: stevenstuartm@gmail.com
description: Software architect sharing practical insights on cloud architecture, system design, AWS, .NET, and building scalable distributed systems.
baseurl: ""
url: "https://stevenstuartm.com"
version: 1.0.3

# Author information
author:
  name: Steven Stuart
  email: stevenstuartm@gmail.com
  github: stevenstuartm
  linkedin: stevenstuartm

# Social media links (add/remove as needed)
social:
  github: https://github.com/stevenstuartm
  linkedin: https://linkedin.com/in/steven-stuart-2974978a

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title/

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-feed

# Feed settings
feed:
  path: feed-blog.xml
  collections:
    - posts

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/
  guides:
    output: true
    permalink: /guides/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "guides"
    values:
      layout: "guide"
  - scope:
      path: ""
    values:
      layout: "default"

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - README.md
  - CLAUDE.md